name: CMake CI for Advent of Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Copy data folder to build
      run: cp -r ${{ github.workspace }}/data ${{ github.workspace }}/build/data

    - name: Run day01
      working-directory: ${{ github.workspace }}/build
      run: ./day01

    - name: Run day02
      working-directory: ${{ github.workspace }}/build
      run: ./day02

    - name: Run day03
      working-directory: ${{ github.workspace }}/build
      run: ./day03

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest --output-on-failure -C ${{ env.BUILD_TYPE }}
